# Generated by Django 4.0.1 on 2022-02-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='points',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='5', max_length=200),
        ),
    ]
